// axios based types
export const GET_MOVIES = 'GET_MOVIES';
export const ADD_MOVIES = 'ADD_MOVIES';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';
export const ADD_MOVIES_SUCCESS = 'ADD_MOVIES_SUCCESS';
export const ADD_MOVIES_FAIL = 'ADD_MOVIES_FAIL';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIE_FAILURE = 'SEARCH_MOVIE_FAILURE';
// downloads
export const ADD_DOWNLOAD = 'ADD_DOWNLOAD';
export const UPDATE_DOWNLOAD_STATUS = 'UPDATE_DOWNLOAD_STATUS';
export const UPDATE_DOWNLOAD_FILL = 'UPDATE_DOWNLOAD_FILL';
export const UPDATE_DOWNLOAD_TASK = 'UPDATE_DOWNLOAD_TASK';
export const CANCEL_DOWNLOAD = 'CANCEL_DOWNLOAD';
// open a movie popup
export const OPEN_MOVIE_POPUP = 'OPEN_MOVIE';
// close movie popup
export const CLOSE_MOVIE_POPUP = 'CLOSE_MOVIE';
// show notifications
export const SHOW_NOTIFICATIONS = 'SHOW_NOTIFICATIONS';
// select engine
export const SELECT_ENGINE = 'SELECT_ENGINE';
export const SELECT_ENGINE_SUCCESS = 'SELECT_ENGINE_SUCCESS';
export const SELECT_ENGINE_FAILURE = 'SELECT_ENGINE_FAILURE';